name: LEGO Checker Workflow

on:
  schedule:
    - cron: "0 8 * * *"  # Spustí se v 8:00 UTC
    - cron: "0 13 * * *" # Spustí se v 13:00 UTC
    - cron: "0 19 * * *" # Spustí se v 19:00 UTC
  workflow_dispatch: # Umožní manuální spuštění

jobs:
  check-lego:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # Verze Pythonu

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: List all files
        run: ls -la      

      - name: Run LEGO Checker
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }} # Načtení hesla z GitHub Secrets
        run: python lego_checker.py

      - name: Check for changes
        run: |
          git status
          ls -la

      - name: Show Git differences
        run: git diff lego_results.csv || echo "No differences found"     

      - name: Commit and push updated CSV
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add lego_results.csv
          git commit -m "Update LEGO results" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Show CSV content
        run: cat lego_results.csv    

      - name: Show Git status
        run: |
          git status
